apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: saeeds
  annotations:
    'github.com/user-login': saeedseyfi
spec:
  profile:
    displayName: Saeed Seyfi
    email: saeeds@spotify.com
    picture: https://avatars.githubusercontent.com/u/5411866
  memberOf: [admin]
